<a href="https://colab.research.google.com/github/Agtna/AI-2025/blob/main/Penugasan_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import pandas as pd

data_pasien = pd.read_csv('data_pasien.csv')

In [110]:
data_pasien.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            10 non-null     int64
 1   Usia          10 non-null     int64
 2   IMT           10 non-null     float64
 3   TekananDarah  10 non-null     int64
 4   Merokok       10 non-null     object
 5   Olahraga      10 non-null     object
 6   Penyakit      10 non-null     object
dtypes: float64(1), int64(3), object(3)
memory usage: 692.0+ bytes

In [111]:
data_pasien.info()

data_pasien.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            10 non-null     int64
 1   Usia          10 non-null     int64
 2   IMT           10 non-null     float64
 3   TekananDarah  10 non-null     int64
 4   Merokok       10 non-null     object
 5   Olahraga      10 non-null     object
 6   Penyakit      10 non-null     object
dtypes: float64(1), int64(3), object(3)
memory usage: 692.0+ bytes

   ID  Usia   IMT  TekananDarah Merokok Olahraga Penyakit
5   6    33  26.2           130   Tidak       Ya    Tidak
6   7    55  28.9           145      Ya    Tidak       Ya
7   8    22  21.7           110   Tidak       Ya    Tidak
8   9    45  29.4           155      Ya    Tidak       Ya
9  10    31  25.6           135   Tidak       Ya    Tidak

In [112]:
data_pasien.isnull().sum()

ID              0
Usia            0
IMT             0
TekananDarah    0
Merokok         0
Olahraga        0
Penyakit        0
dtype: int64

In [113]:
data_pasien['Merokok'] = data_pasien['Merokok'].map({'Ya': 1, 'Tidak' : 0})

data_pasien['Olahraga'] = data_pasien['Olahraga'].map({'Ya': 1, 'Tidak': 0})

data_pasien['Penyakit'] = data_pasien['Penyakit'].map({'Ya' : 1, 'Tidak' : 0})

In [114]:
data_pasien.tail()

   ID  Usia   IMT  TekananDarah  Merokok  Olahraga  Penyakit
5   6    33  26.2           130        0         1         0
6   7    55  28.9           145        1         0         1
7   8    22  21.7           110        0         1         0
8   9    45  29.4           155        1         0         1
9  10    31  25.6           135        0         1         0

In [115]:
data_pasien.drop('ID',axis=1, inplace=True)

In [116]:
data_pasien.tail()

   Usia   IMT  TekananDarah  Merokok  Olahraga  Penyakit
5    33  26.2           130        0         1         0
6    55  28.9           145        1         0         1
7    22  21.7           110        0         1         0
8    45  29.4           155        1         0         1
9    31  25.6           135        0         1         0

In [117]:
x = data_pasien[['Usia', 'IMT','TekananDarah', 'Merokok', 'Olahraga']]
y = data_pasien['Penyakit']

In [118]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=99)

In [119]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [120]:
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier()

tree_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [121]:
from sklearn.metrics import accuracy_score

y_pred = tree_model.predict(x_test)

acc_score = round(accuracy_score(y_pred, y_test), 3)

print('Accuracy: ', acc_score)

Accuracy:  1.0

In [122]:
from sklearn. tree import export_graphviz
export_graphviz(
    tree_model,
    out_file = "tree_model.dot",
    feature_names = ['Usia', 'IMT', 'TekananDarah', 'Merokok', 'Olahraga'],
    class_names = ['Tidak', 'Ya'],
    rounded= True,
    filled =True
)